Repository NOW-SOPT-CDSP-WEB5/CGV-SERVER, pull requests merged in 2024-05, with the labels that each got.

#2 [feat] CI/CD 설정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  src/main/resources/application-ex.yml
Labels: 상준, 가연

#5 [feat] 영화 디테일 api 구현
  build.gradle
  src/main/java/org/sopt/cgv/config/SwaggerConfig.java
  src/main/java/org/sopt/cgv/controller/MovieController.java
  src/main/java/org/sopt/cgv/controller/MovieControllerSwagger.java
  src/main/java/org/sopt/cgv/domain/Movie.java
  src/main/java/org/sopt/cgv/repository/MovieRepository.java
  src/main/java/org/sopt/cgv/service/MovieService.java
  src/main/java/org/sopt/cgv/service/dto/MovieDetailRequestDto.java
Labels: 가연, api

#21 [feat] 광고 목록 API
  src/main/java/org/sopt/cgv/controller/AdvertisementController.java
  src/main/java/org/sopt/cgv/domain/Advertisement.java
  src/main/java/org/sopt/cgv/dto/AdDto.java
  src/main/java/org/sopt/cgv/dto/AdsDto.java
  src/main/java/org/sopt/cgv/repository/AdvertisementRepository.java
  src/main/java/org/sopt/cgv/service/AdvertisementService.java
Labels: 상준, api

#22 [feat] #19 create movies API
  src/main/java/org/sopt/cgv/controller/MovieController.java
  src/main/java/org/sopt/cgv/dto/MovieDto.java
  src/main/java/org/sopt/cgv/dto/MoviesDto.java
  src/main/java/org/sopt/cgv/service/MovieService.java
Labels: 상준, api

#23 [feat] 상영관-상영시간 조회 API 생성
  src/main/java/org/sopt/cgv/controller/TheaterController.java
  src/main/java/org/sopt/cgv/domain/Cinema.java
  src/main/java/org/sopt/cgv/domain/Theater.java
  src/main/java/org/sopt/cgv/dto/TheaterCinemaDto.java
  src/main/java/org/sopt/cgv/dto/TheaterDto.java
  src/main/java/org/sopt/cgv/dto/TheaterMovieDto.java
  src/main/java/org/sopt/cgv/dto/TheaterTimeDto.java
  src/main/java/org/sopt/cgv/dto/TheaterTopDto.java
  src/main/java/org/sopt/cgv/repository/MovieRepository.java
  src/main/java/org/sopt/cgv/repository/TheaterRepository.java
  src/main/java/org/sopt/cgv/service/TheaterService.java
Labels: 상준, api

#25 [fix] #25 fix query in movies API
  src/main/java/org/sopt/cgv/repository/MovieRepository.java
  src/main/java/org/sopt/cgv/service/MovieService.java
Labels: 상준

#27 [fix] #26 Swagger Cors 에러 해결
  src/main/java/org/sopt/cgv/CgvApplication.java
Labels: 가연

#29 [refac] #28 코드리뷰 반영
  src/main/java/org/sopt/cgv/controller/MovieController.java
  src/main/java/org/sopt/cgv/controller/MovieControllerSwagger.java
Labels: 가연
